package com.project.findme.utils

import android.graphics.Color
import com.ryan.findme.R

object Constants {
    const val DEFAULT_PROFILE_PICTURE_URL =
        "https://firebasestorage.googleapis.com/v0/b/social-network-662a2.appspot.com/o/avatar.png?alt=media&token=69f56ce2-8fe2-4051-9e61-9e52182384c9"
    const val SLACK_COMMUNITY_JOINING_LINK =
        "https://join.slack.com/t/teamfindme/shared_invite/zt-19skou62t-8~rxwg3kFyRwL6XqPxgkgQ"
    const val MAX_USERNAME_LENGTH = 8
    const val MIN_USERNAME_LENGTH = 3
    const val MIN_PASSWORD_LENGTH = 8
    const val SEARCH_TIME_DELAY = 500L
    const val FRAGMENT_ARG_KEY = "FRAGMENT_ARG_KEY"
    const val PAGE_SIZE = 5
    val FRAGMENTS_LIST = listOf(
        R.id.editProfileFragment,
        R.id.draftPostFragment,
        R.id.changePasswordFragment,
        R.id.searchedProfileFragment,
        R.id.listFollowersFragment,
        R.id.listFollowersFragmentUser,
        R.id.commentFragment,
        R.id.likedByFragment,
        R.id.chatWindowFragment,
        R.id.allUsers
    )
    val FRAGMENTS_LIST_BOTTOM_NAV = listOf(
        R.id.editProfileFragment,
        R.id.draftPostFragment,
        R.id.changePasswordFragment,
        R.id.searchedProfileFragment,
        R.id.listFollowersFragment,
        R.id.listFollowersFragmentUser,
        R.id.commentFragment,
        R.id.likedByFragment,
        R.id.createPostFragment,
        R.id.createTextPostFragment,
        R.id.chatWindowFragment,
        R.id.allUsers
    )
    val COLORS = mapOf(
        0 to R.drawable.blue_background,
        1 to R.drawable.red_background,
        2 to R.drawable.peach_background,
        3 to R.drawable.yellow_background,
        4 to R.drawable.brown_background
    )
    val PEN_COLORS = mapOf(
        0 to Color.RED,
        1 to Color.CYAN,
        2 to Color.BLUE,
        3 to Color.MAGENTA,
        4 to Color.YELLOW,
        5 to Color.WHITE
    )
    val HOBBIES = arrayOf(
        "3d printing",
        "amateur meteorology",
        "art collecting",
        "astronomy",
        "backpacking travel",
        "bartending",
        "base jumping",
        "beekeeping",
        "billiards",
        "bird watching",
        "blogging",
        "book collecting",
        "bowling",
        "build model rockets",
        "camping",
        "candle-making",
        "choreography",
        "climbing",
        "collecting autograph",
        "collecting cards",
        "collecting coins",
        "collecting comic books",
        "collecting dolls",
        "collecting insects",
        "collecting records",
        "collecting stamps",
        "collecting video games",
        "computer programming",
        "cooking specialty foods",
        "crocheting",
        "cubing",
        "dancing",
        "dowsing",
        "drone",
        "electronics",
        "equestrianism",
        "fantasy sports",
        "fashion",
        "fishing",
        "flower arranging",
        "flying",
        "foraging",
        "fossil hunting",
        "gardening",
        "geocaching",
        "ghost hunting",
        "graffiti art",
        "gymnastics",
        "herping",
        "high-power rocketry",
        "hiking",
        "hunting",
        "hydroponic gardening",
        "ice skating",
        "interior decorating",
        "jogging",
        "kart racing",
        "kayaking",
        "knitting",
        "martial arts",
        "meditation",
        "metal detecting",
        "microscopy",
        "mineral collecting",
        "model building",
        "mountain biking",
        "mountaineering",
        "movie collecting",
        "mushroom hunting",
        "observation hobby",
        "painting",
        "paper making",
        "parkour",
        "photography",
        "ping pong",
        "playing board games",
        "pottery",
        "quilting",
        "racing",
        "reading",
        "river rafting",
        "road biking",
        "robotics",
        "running",
        "sailing",
        "sand art",
        "scouting",
        "scuba diving",
        "sculpting",
        "sewing",
        "shopping",
        "skateboarding",
        "skiing",
        "soap-making",
        "social media",
        "social networking",
        "speedcubing",
        "surfing",
        "swimming",
        "taxidermy",
        "table tennis",
        "technology gadgets",
        "topiary",
        "treasure hunting",
        "urban exploration",
        "video gaming",
        "walking",
        "weightlifting",
        "whale watching",
        "wine collecting",
        "worldbuilding",
        "writing",
        "yoga"
    )

    val PROFFESSIONS = arrayOf(
        "accountant",
        "actor",
        "actress",
        "air traffic controller",
        "architect",
        "artist",
        "attorney",
        "banker",
        "bartender",
        "barber",
        "bookkeeper",
        "builder",
        "businessman",
        "businesswoman",
        "businessperson",
        "butcher",
        "carpenter",
        "cashier",
        "chef",
        "coach",
        "dental hygienist",
        "dentist",
        "designer",
        "developer",
        "dietitian",
        "doctor",
        "economist",
        "editor",
        "electrician",
        "engineer",
        "farmer",
        "filmmaker",
        "fisherman",
        "flight attendant",
        "jeweler",
        "judge",
        "lawyer",
        "mechanic",
        "musician",
        "nutritionist",
        "nurse",
        "optician",
        "painter",
        "pharmacist",
        "photographer",
        "physician",
        "physician's assistant",
        "pilot",
        "plumber",
        "police officer",
        "politician",
        "professor",
        "programmer",
        "psychologist",
        "receptionist",
        "salesman",
        "salesperson",
        "saleswoman",
        "secretary",
        "singer",
        "student",
        "surgeon",
        "teacher",
        "therapist",
        "translator",
        "translator",
        "undertaker",
        "veterinarian",
        "videographer",
        "waiter",
        "waitress",
        "writer"
    )
}